// without unit
export const WIDE_DESKTOP_COLUMNS = 12;
export const NARROW_DESKTOP_COLUMNS = 8;
export const TABLET_COLUMNS = 6;
export const MOBILE_COLUMNS = 4;

// unit: rem
export const WIDE_DESKTOP_HEADER_HEIGHT = 6.4;
export const WIDE_DESKTOP_HEADLINE_PADDING_TOP = 20;
export const WIDE_DESKTOP_HEADLINE_PADDING_BOTTOM = 25;
export const WIDE_DESKTOP_MAX_WIDTH = 114;
export const WIDE_DESKTOP_CONTENT_PADDING_TOP = 15.6;

export const NARROW_DESKTOP_HEADLINE_PADDING_TOP = 17;
export const NARROW_DESKTOP_HEADLINE_PADDING_BOTTOM = 22;
export const NARROW_DESKTOP_MAX_WIDTH = 96;
export const NARROW_DESKTOP_CONTENT_PADDING_TOP = 13.5;

export const TABLET_HEADLINE_PADDING_TOP = 13.5;
export const TABLET_HEADLINE_PADDING_BOTTOM = 19;
export const TABLET_MAX_WIDTH = 72;
export const TABLET_CONTENT_PADDING_TOP = 11;

export const MOBILE_HEADLINE_PADDING_TOP = 10;
export const MOBILE_HEADLINE_PADDING_BOTTOM = 15;
export const MOBILE_MAX_WIDTH = 54;
export const MOBILE_CONTENT_PADDING_TOP = 9;

export const HEADLINE_BACKGROUND_COLOR = '#F2F2F2';

export const PAGE_PADDING = 2;
